# Generated by Django 3.1.4 on 2021-02-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
